"""Blocks autonomous git history mutation during orchestrated OpenClaw execution.

Phase 22C-0 containment. OpenClaw's own agent loop executes arbitrary shell
commands with the operator's ambient git identity, and nothing in Orchestrator
intercepts those commands in flight -- `git` is not routed through
Orchestrator's own step validator (`workspace_guard.py`) at all when the
OpenClaw backend is in use. Phase 22B Cycle 3 showed prompt-level scoping does
not reliably prevent this: a narrowly-scoped bug-fix task ran an unrequested
`git commit` that swept a different task's broken partial edit into `main`
under the operator's real identity (commit `9f4168e`).

This installs a `git` shim ahead of the real binary on PATH for the OpenClaw
subprocess only, so mutating subcommands are refused at the process boundary
instead of merely discouraged in the prompt. Read-only commands (status, diff,
log, show, add, ...) pass through unchanged.

No existing mechanism in this codebase lets a task carry an explicit
"git mutation authorized" flag (see the Phase 22C-0 report for that gap), so
the guard blocks unconditionally today. Wiring a real per-task authorization
on-ramp is left to Phase 23.
"""

from __future__ import annotations

import logging
import os
import shutil
import stat
import tempfile
from pathlib import Path
from typing import Dict, Optional, Tuple

logger = logging.getLogger(__name__)

# Subcommands that mutate history or refs and are always blocked.
BLOCKED_GIT_MUTATION_SUBCOMMANDS = (
    "commit",
    "push",
    "pull",
    "rebase",
    "merge",
    "reset",
    "checkout",
    "switch",
)

GIT_CONTAINMENT_ACTIVE_ENV_VAR = "ORCHESTRATOR_GIT_CONTAINMENT_ACTIVE"

_SHIM_TEMPLATE = """#!/usr/bin/env bash
# Generated by Orchestrator Phase 22C-0 git containment guard.
# Regenerated per OpenClaw invocation and discarded afterward -- do not edit.
set -euo pipefail
REAL_GIT={real_git}
sub="${{1:-}}"

deny() {{
  echo "orchestrator: git $1 is blocked during orchestrated execution (Phase 22C-0 git containment). The operator owns repository history; this action was not authorized by an explicit review policy." >&2
  exit 1
}}

case "$sub" in
  commit|push|pull|rebase|merge|reset|checkout|switch)
    deny "$sub"
    ;;
  branch)
    for arg in "$@"; do
      case "$arg" in
        -d|-D|--delete|--delete=*)
          deny "branch (delete)"
          ;;
      esac
    done
    exec "$REAL_GIT" "$@"
    ;;
  config)
    case "${{2:-}}" in
      --get|--get-all|--get-regexp|--get-urlmatch|--list|-l|--list-all|--show-origin|--show-scope|--name-only|-h|--help|"")
        exec "$REAL_GIT" "$@"
        ;;
      *)
        deny "config (write)"
        ;;
    esac
    ;;
  *)
    exec "$REAL_GIT" "$@"
    ;;
esac
"""


def _shell_single_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def build_git_containment_env(
    base_env: Optional[Dict[str, str]] = None,
) -> Tuple[Dict[str, str], Optional[Path]]:
    """Return an env dict that routes `git` through the mutation-blocking shim.

    Returns ``(env, shim_dir)``. ``shim_dir`` is ``None`` (and ``env`` is the
    unmodified base env) if a real `git` binary cannot be located on the
    resolved PATH -- there is nothing to guard, and refusing to run OpenClaw
    entirely over an unrelated PATH problem would be a disproportionate
    failure mode for this bounded containment.
    """

    env = dict(base_env if base_env is not None else os.environ)
    real_git = shutil.which("git", path=env.get("PATH"))
    if not real_git:
        logger.warning(
            "[GIT_CONTAINMENT] No git binary found on PATH; git containment "
            "shim not installed for this invocation."
        )
        return env, None

    shim_dir = Path(tempfile.mkdtemp(prefix="orchestrator-git-guard-"))
    shim_path = shim_dir / "git"
    shim_path.write_text(
        _SHIM_TEMPLATE.format(real_git=_shell_single_quote(real_git)),
        encoding="utf-8",
    )
    mode = shim_path.stat().st_mode
    shim_path.chmod(mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    env["PATH"] = f"{shim_dir}{os.pathsep}{env.get('PATH', '')}"
    env[GIT_CONTAINMENT_ACTIVE_ENV_VAR] = "1"
    return env, shim_dir


def cleanup_git_containment_shim(shim_dir: Optional[Path]) -> None:
    """Best-effort removal of the temporary shim directory."""

    if not shim_dir:
        return
    try:
        shutil.rmtree(shim_dir, ignore_errors=True)
    except Exception:
        logger.debug(
            "[GIT_CONTAINMENT] Failed to clean up shim dir %s",
            shim_dir,
            exc_info=True,
        )
